//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSintez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_steps
    {
        public int id { get; set; }
        public int batch_id { get; set; }
        public int tech_card_step_id { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public int step_number { get; set; }
        public string step_name { get; set; }
        public Nullable<int> planned_temperature { get; set; }
        public Nullable<int> actual_temperature { get; set; }
        public Nullable<int> planned_duration_min { get; set; }
        public Nullable<int> actual_duration_min { get; set; }
        public Nullable<decimal> planned_pressure { get; set; }
        public Nullable<decimal> actual_pressure { get; set; }
        public Nullable<int> has_deviation { get; set; }
        public string deviation_description { get; set; }
        public string operator_comment { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
    
        public virtual production_batches production_batches { get; set; }
        public virtual equipment equipment { get; set; }
        public virtual tech_card_steps tech_card_steps { get; set; }
    }
}
