//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSintez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formula_components
    {
        public int id { get; set; }
        public int recipe_id { get; set; }
        public int raw_material_id { get; set; }
        public decimal percentage { get; set; }
        public int loading_order { get; set; }
        public Nullable<decimal> deviation_tolerance { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual raw_materials raw_materials { get; set; }
        public virtual recipes recipes { get; set; }
    }
}
