//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSintez.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgroSintezEntities : DbContext
    {
        public AgroSintezEntities()
            : base("name=AgroSintezEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch_steps> batch_steps { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<formula_components> formula_components { get; set; }
        public virtual DbSet<notifications> notifications { get; set; }
        public virtual DbSet<production_batches> production_batches { get; set; }
        public virtual DbSet<production_orders> production_orders { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<quality_control> quality_control { get; set; }
        public virtual DbSet<raw_material_batches> raw_material_batches { get; set; }
        public virtual DbSet<raw_materials> raw_materials { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tech_card_steps> tech_card_steps { get; set; }
        public virtual DbSet<technological_cards> technological_cards { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
