//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSintez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifications
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public Nullable<int> is_read { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual users users { get; set; }
    }
}
