//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSintez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raw_material_batches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public raw_material_batches()
        {
            this.quality_control = new HashSet<quality_control>();
        }
    
        public int id { get; set; }
        public string batch_number { get; set; }
        public int raw_material_id { get; set; }
        public decimal quantity { get; set; }
        public string unit_of_measure { get; set; }
        public System.DateTime receipt_date { get; set; }
        public string supplier { get; set; }
        public string lab_status { get; set; }
        public Nullable<int> used_in_production_batch_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual production_batches production_batches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quality_control> quality_control { get; set; }
        public virtual raw_materials raw_materials { get; set; }
    }
}
