//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSintez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipes()
        {
            this.formula_components = new HashSet<formula_components>();
            this.production_orders = new HashSet<production_orders>();
        }
    
        public int id { get; set; }
        public int product_id { get; set; }
        public string name { get; set; }
        public int version { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> created_by_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formula_components> formula_components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_orders> production_orders { get; set; }
        public virtual products products { get; set; }
        public virtual users users { get; set; }
    }
}
