//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSintez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tech_card_steps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tech_card_steps()
        {
            this.batch_steps = new HashSet<batch_steps>();
        }
    
        public int id { get; set; }
        public int tech_card_id { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public int step_number { get; set; }
        public string step_name { get; set; }
        public string step_type { get; set; }
        public Nullable<int> planned_temp_min { get; set; }
        public Nullable<int> planned_temp_max { get; set; }
        public int planned_duration_min { get; set; }
        public Nullable<decimal> planned_pressure_min { get; set; }
        public Nullable<decimal> planned_pressure_max { get; set; }
        public Nullable<int> is_mandatory { get; set; }
        public string instruction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_steps> batch_steps { get; set; }
        public virtual equipment equipment { get; set; }
        public virtual technological_cards technological_cards { get; set; }
    }
}
